project:
  type: website
  output-dir: docs

website:
  title: "ELZ Ming"
  navbar:
    logo: "image/sit-logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: hobby.qmd
        text: Hobby
      - href: reflection.qmd
        text: Reflection
        
format:
  html:
    theme: cosmo
    css: styles.css


