project:
  type: website
  output-dir: _site 
  
website:
  title: "ApplePie's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: trip.qmd
        text: Trip
      - href: reflection.qmd
        text: Reflection